// FPL Draft Player Database — Premier League Scout Top 100 + extended coverage
// Source: premierleague.com FPL Draft Top 100 rankings (Aug 2026) + all PL squads
export const FPL_PLAYERS = [
  { rank: 1, name: "Erling Haaland", team: "Man City", pos: "FWD" },
  { rank: 2, name: "Bruno Fernandes", team: "Man Utd", pos: "MID" },
  { rank: 3, name: "Gabriel", team: "Arsenal", pos: "DEF" },
  { rank: 4, name: "Joao Pedro", team: "Chelsea", pos: "FWD" },
  { rank: 5, name: "Cole Palmer", team: "Chelsea", pos: "MID" },
  { rank: 6, name: "Bukayo Saka", team: "Arsenal", pos: "MID" },
  { rank: 7, name: "Igor Thiago", team: "Brentford", pos: "FWD" },
  { rank: 8, name: "Dominik Szoboszlai", team: "Liverpool", pos: "MID" },
  { rank: 9, name: "Bryan Mbeumo", team: "Man Utd", pos: "MID" },
  { rank: 10, name: "Florian Wirtz", team: "Liverpool", pos: "MID" },
  { rank: 11, name: "Alexander Isak", team: "Liverpool", pos: "FWD" },
  { rank: 12, name: "Matheus Cunha", team: "Man Utd", pos: "MID" },
  { rank: 13, name: "Morgan Gibbs-White", team: "Nott. Forest", pos: "MID" },
  { rank: 14, name: "David Raya", team: "Arsenal", pos: "GK" },
  { rank: 15, name: "Phil Foden", team: "Man City", pos: "MID" },
  { rank: 16, name: "Morgan Rogers", team: "Chelsea", pos: "MID" },
  { rank: 17, name: "Josko Gvardiol", team: "Man City", pos: "DEF" },
  { rank: 18, name: "Declan Rice", team: "Arsenal", pos: "MID" },
  { rank: 19, name: "Virgil van Dijk", team: "Liverpool", pos: "DEF" },
  { rank: 20, name: "Viktor Gyokeres", team: "Arsenal", pos: "FWD" },
  { rank: 21, name: "Antoine Semenyo", team: "Man City", pos: "MID" },
  { rank: 22, name: "Ollie Watkins", team: "Aston Villa", pos: "FWD" },
  { rank: 23, name: "Elliot Anderson", team: "Man City", pos: "MID" },
  { rank: 24, name: "Nico O'Reilly", team: "Man City", pos: "DEF" },
  { rank: 25, name: "Jean-Philippe Mateta", team: "Crystal Palace", pos: "FWD" },
  { rank: 26, name: "Marc Guehi", team: "Man City", pos: "DEF" },
  { rank: 27, name: "Dominic Calvert-Lewin", team: "Leeds", pos: "FWD" },
  { rank: 28, name: "Neco Williams", team: "Nott. Forest", pos: "DEF" },
  { rank: 29, name: "Pedro Porro", team: "Spurs", pos: "DEF" },
  { rank: 30, name: "Igor Jesus", team: "Nott. Forest", pos: "FWD" },
  { rank: 31, name: "Harry Wilson", team: "Leeds", pos: "FWD" },
  { rank: 32, name: "Alisson Becker", team: "Liverpool", pos: "GK" },
  { rank: 33, name: "Maxence Lacroix", team: "Chelsea", pos: "DEF" },
  { rank: 34, name: "James Tarkowski", team: "Everton", pos: "DEF" },
  { rank: 35, name: "Ismaila Sarr", team: "Crystal Palace", pos: "MID" },
  { rank: 36, name: "Gianluigi Donnarumma", team: "Man City", pos: "GK" },
  { rank: 37, name: "Adrien Truffert", team: "Bournemouth", pos: "DEF" },
  { rank: 38, name: "Daniel Munoz", team: "Crystal Palace", pos: "DEF" },
  { rank: 39, name: "Nikola Milenkovic", team: "Nott. Forest", pos: "DEF" },
  { rank: 40, name: "Bruno Guimaraes", team: "Arsenal", pos: "MID" },
  { rank: 41, name: "Evanilson", team: "Bournemouth", pos: "FWD" },
  { rank: 42, name: "Cody Gakpo", team: "Liverpool", pos: "MID" },
  { rank: 43, name: "Martin Odegaard", team: "Arsenal", pos: "MID" },
  { rank: 44, name: "Murillo", team: "Nott. Forest", pos: "DEF" },
  { rank: 45, name: "Richarlison", team: "Spurs", pos: "FWD" },
  { rank: 46, name: "Brian Brobbey", team: "Sunderland", pos: "FWD" },
  { rank: 47, name: "Iliman Ndiaye", team: "Everton", pos: "MID" },
  { rank: 48, name: "Pascal Gross", team: "Brighton", pos: "MID" },
  { rank: 49, name: "Caoimhin Kelleher", team: "Brentford", pos: "GK" },
  { rank: 50, name: "Benjamin Sesko", team: "Man Utd", pos: "FWD" },
  { rank: 51, name: "Marcus Tavernier", team: "Bournemouth", pos: "MID" },
  { rank: 52, name: "Enzo Fernandez", team: "Chelsea", pos: "MID" },
  { rank: 53, name: "Jordan Pickford", team: "Everton", pos: "GK" },
  { rank: 54, name: "Jeremie Frimpong", team: "Liverpool", pos: "DEF" },
  { rank: 55, name: "Nordi Mukiele", team: "Sunderland", pos: "DEF" },
  { rank: 56, name: "Jan Paul van Hecke", team: "Spurs", pos: "DEF" },
  { rank: 57, name: "Alex Scott", team: "Bournemouth", pos: "MID" },
  { rank: 58, name: "Enzo Le Fee", team: "Sunderland", pos: "MID" },
  { rank: 59, name: "Mamadou Sangare", team: "Brentford", pos: "MID" },
  { rank: 60, name: "Kaoru Mitoma", team: "Brighton", pos: "MID" },
  { rank: 61, name: "Youri Tielemans", team: "Man Utd", pos: "MID" },
  { rank: 62, name: "Dango Ouattara", team: "Brentford", pos: "MID" },
  { rank: 63, name: "Yoane Wissa", team: "Newcastle", pos: "FWD" },
  { rank: 64, name: "Johan Manzambi", team: "Aston Villa", pos: "MID" },
  { rank: 65, name: "Antonin Kinsky", team: "Spurs", pos: "GK" },
  { rank: 66, name: "Oli McBurnie", team: "Hull", pos: "FWD" },
  { rank: 67, name: "Anton Stach", team: "Leeds", pos: "MID" },
  { rank: 68, name: "Robin Roefs", team: "Sunderland", pos: "GK" },
  { rank: 69, name: "Micky van de Ven", team: "Spurs", pos: "DEF" },
  { rank: 70, name: "Kai Havertz", team: "Arsenal", pos: "FWD" },
  { rank: 71, name: "Rayan Cherki", team: "Man City", pos: "MID" },
  { rank: 72, name: "Mateus Fernandes", team: "Spurs", pos: "MID" },
  { rank: 73, name: "Djordje Petrovic", team: "Bournemouth", pos: "GK" },
  { rank: 74, name: "Jeremy Doku", team: "Man City", pos: "MID" },
  { rank: 75, name: "Jurrien Timber", team: "Arsenal", pos: "DEF" },
  { rank: 76, name: "Senne Lammens", team: "Man Utd", pos: "GK" },
  { rank: 77, name: "Luke Shaw", team: "Man Utd", pos: "DEF" },
  { rank: 78, name: "Noah Okafor", team: "Leeds", pos: "MID" },
  { rank: 79, name: "John McGinn", team: "Aston Villa", pos: "MID" },
  { rank: 80, name: "Alexis Mac Allister", team: "Liverpool", pos: "MID" },
  { rank: 81, name: "Ezri Konsa", team: "Aston Villa", pos: "DEF" },
  { rank: 82, name: "Milos Kerkez", team: "Liverpool", pos: "DEF" },
  { rank: 83, name: "Sandro Tonali", team: "Spurs", pos: "MID" },
  { rank: 84, name: "Harvey Barnes", team: "Newcastle", pos: "MID" },
  { rank: 85, name: "Harry Maguire", team: "Man Utd", pos: "DEF" },
  { rank: 86, name: "Lewis Hall", team: "Newcastle", pos: "DEF" },
  { rank: 87, name: "James Maddison", team: "Spurs", pos: "MID" },
  { rank: 88, name: "James Garner", team: "Everton", pos: "MID" },
  { rank: 89, name: "Riccardo Calafiori", team: "Arsenal", pos: "DEF" },
  { rank: 90, name: "Jack Hinshelwood", team: "Brighton", pos: "MID" },
  { rank: 91, name: "Cristhian Mosquera", team: "Arsenal", pos: "DEF" },
  { rank: 92, name: "Matty Cash", team: "Aston Villa", pos: "DEF" },
  { rank: 93, name: "Gonzalo Garcia", team: "Fulham", pos: "FWD" },
  { rank: 94, name: "Nathan Collins", team: "Brentford", pos: "DEF" },
  { rank: 95, name: "Kiernan Dewsbury-Hall", team: "Everton", pos: "MID" },
  { rank: 96, name: "Kevin Schade", team: "Brentford", pos: "MID" },
  { rank: 97, name: "Mohammed Kudus", team: "Spurs", pos: "MID" },
  { rank: 98, name: "Alejandro Garnacho", team: "Aston Villa", pos: "MID" },
  { rank: 99, name: "Emersonn", team: "Ipswich", pos: "FWD" },
  { rank: 100, name: "Dominic Solanke", team: "Spurs", pos: "FWD" },
  { rank: 121, name: "Rayan", team: "Bournemouth", pos: "FWD" },
  { rank: 122, name: "Philippe Coutinho", team: "Bournemouth", pos: "MID" },
  { rank: 123, name: "Mikel Merino", team: "Arsenal", pos: "MID" },
  { rank: 125, name: "Son Heung-min", team: "Spurs", pos: "FWD" },
  { rank: 129, name: "Luis Diaz", team: "Liverpool", pos: "MID" },
  { rank: 131, name: "Justin Kluivert", team: "Bournemouth", pos: "MID" },
  { rank: 136, name: "Malick Thiaw", team: "Newcastle", pos: "DEF" },
  { rank: 143, name: "Christos Tzolis", team: "Arsenal", pos: "MID" },
  { rank: 144, name: "Matthijs de Ligt", team: "Man Utd", pos: "DEF" },
  { rank: 146, name: "Trent Alexander-Arnold", team: "Liverpool", pos: "DEF" },
  { rank: 149, name: "William Saliba", team: "Arsenal", pos: "DEF" },
  { rank: 151, name: "Ruben Dias", team: "Man City", pos: "DEF" },
  { rank: 170, name: "Chris Wood", team: "Nott. Forest", pos: "FWD" },
  { rank: 172, name: "Jhon Duran", team: "Aston Villa", pos: "FWD" },
  { rank: 176, name: "Nicolas Jackson", team: "Chelsea", pos: "FWD" },
  { rank: 179, name: "Darwin Nunez", team: "Liverpool", pos: "FWD" },
  { rank: 184, name: "Michael Olise", team: "Chelsea", pos: "MID" },
  { rank: 186, name: "Anthony Gordon", team: "Newcastle", pos: "MID" },
  { rank: 189, name: "Dejan Kulusevski", team: "Spurs", pos: "MID" },
  { rank: 194, name: "Christopher Nkunku", team: "Chelsea", pos: "FWD" },
  { rank: 195, name: "Pedro Neto", team: "Chelsea", pos: "MID" },
  { rank: 197, name: "Kevin De Bruyne", team: "Man City", pos: "MID" },
  { rank: 202, name: "Ryan Gravenberch", team: "Liverpool", pos: "MID" },
  { rank: 205, name: "Emiliano Martinez", team: "Aston Villa", pos: "GK" },
  { rank: 206, name: "Andre Onana", team: "Man Utd", pos: "GK" },
  { rank: 241, name: "Mikkel Damsgaard", team: "Brentford", pos: "MID" },
  { rank: 242, name: "Emiliano Buendia", team: "Aston Villa", pos: "MID" },
  { rank: 243, name: "Patrick Dorgu", team: "Man Utd", pos: "DEF" },
  { rank: 244, name: "Mathys Tel", team: "Spurs", pos: "FWD" },
  { rank: 245, name: "Nick Woltemade", team: "Newcastle", pos: "FWD" },
  { rank: 246, name: "Yeremy Pino", team: "Crystal Palace", pos: "MID" },
  { rank: 247, name: "Reece James", team: "Chelsea", pos: "DEF" },
  { rank: 248, name: "Estevao", team: "Chelsea", pos: "MID" },
  { rank: 249, name: "James Hill", team: "Bournemouth", pos: "DEF" },
  { rank: 250, name: "Piero Hincapie", team: "Arsenal", pos: "DEF" },
  { rank: 251, name: "Amad Diallo", team: "Man Utd", pos: "MID" },
  { rank: 334, name: "Mohamed Salah", team: "Liverpool", pos: "MID" },
  { rank: 367, name: "Jack Clarke", team: "Sunderland", pos: "MID" },
  { rank: 368, name: "Jobe Bellingham", team: "Sunderland", pos: "MID" },
  { rank: 399, name: "Granit Xhaka", team: "Sunderland", pos: "MID" },
  { rank: 400, name: "Dan Ballard", team: "Sunderland", pos: "DEF" },
  { rank: 401, name: "Trai Hume", team: "Sunderland", pos: "DEF" },
  { rank: 402, name: "Mats Wieffer", team: "Brighton", pos: "MID" },
  { rank: 403, name: "Gabriel Martinelli", team: "Arsenal", pos: "MID" },
  { rank: 404, name: "William Osula", team: "Newcastle", pos: "FWD" },
  { rank: 405, name: "Jacob Murphy", team: "Newcastle", pos: "MID" },
  { rank: 406, name: "Junior Kroupi", team: "Bournemouth", pos: "FWD" },
];
